version: 2.1
orbs:
  release-management: salesforce/npm-release-management@4
workflows:
  version: 2
  test-and-release:
    jobs:
      - release-management/validate-pr:
          filters:
            branches:
              ignore: main
      #              SDR deploys not compatible with Node 16
      #      - release-management/test-package:
      #          name: node-latest
      #          node_version: latest
      - release-management/test-package:
          name: node-lts
          node_version: lts
      - release-management/test-nut:
          name: nuts-on-linux
          node_version: lts
          size: large
          sfdx_version: latest
          requires:
            - node-lts
      - release-management/test-nut:
          name: nuts-on-windows
          sfdx_version: latest
          size: large
          node_version: lts
          os: windows
          requires:
            - node-lts
      - release-management/release-package:
          sign: true
          github-release: true
          requires:
            - node-lts
          filters:
            branches:
              only: main
  test-ts-update:
    triggers:
      - schedule:
          cron: 0 0 * * *
          filters:
            branches:
              only:
                - main
    jobs:
      - release-management/test-ts-update
